controllers/CityController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cities;
use app\models\CitySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\filters\AccessControl;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CityController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'ajax', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'ajax', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

        
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cities models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CitySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cities model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Cities();
        if ( 
            Yii::$app->request->post()
            && Yii::$app->request->isAjax
            )   {
            $_POST['name'] = Html::encode($_POST['name']);
            $model->name = $_POST['name'];
            if(!$model->validate()) {
                print_r(json_encode($model->getErrors()));
                exit();
            }
            if($model->save()) {
               print_r(json_encode('success'));
               exit();
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Cities model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ( $model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    public function actionAjax()
    {
        if (!empty($_POST) && $_POST['id']) {
            if (Yii::$app->request->post() && Yii::$app->request->isAjax) {
                $model = $this->findModel($_POST['id']);
                $_POST['name'] = Html::encode($_POST['name']);
                $model->name = $_POST['name'];
                if (!$model->validate()) {        
                    print_r(json_encode($model->getErrors()));
                    exit();
                }
                if ($model->save()) {
                   print_r(json_encode('success'));
                   exit();
                }
            }            
        };    
    }

    /**
     * Deletes an existing Cities model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete()
    {     
        if (!empty($_POST)) {
           $this->findModel((int)$_POST['id'])->delete();
            print_r (json_encode('success'));
            exit();
        }
        die('fail');
    }

    /**
     * Finds the Cities model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cities the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cities::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/city/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

if (isset($_GET['id'])) {
    $this->title = Yii::t('app', 'Редактировать');
} else {
    $this->title = Yii::t('app', 'Добавить категорию');
}

/* @var $this yii\web\View */
/* @var $model app\models\Cities */
/* @var $form yii\widgets\ActiveForm */
?>

<h1 class="my-md-5 my-4"><?= Html::encode($this->title) ?></h1>
<div class="row">
    <div class="col-lg-5 col-md-8">
        <?php if (isset($_GET['id'])): ?>
        <form class="parent">
            <div class="form-floating mb-3">
                <input name="name" type="text" class="form-control name" placeholder="Напишите название"
                    id="floatingName">
                <label id="label_name" for="floatingName">
                    <?= !empty($model->name) ? $model->name : 'Название'?></label>
                <div class="invalid-feedback name_error">
                    Пожалуйста, выберите корректное значение
                </div>
            </div>

            <button data-id="<?= $model->id?>" id="update" class="btn btn-primary">Добавить</button>

        </form>
        <?php endif; ?>
        <?php if (!isset($_GET['id'])): ?>
        <form class="parent">
            <div class="form-floating mb-3">
                <input name="name" type="text" class="form-control name" placeholder="Напишите название"
                    id="floatingName">
                <label id="label_name" for="floatingName">
                    <?= !empty($model->name) ? $model->name : 'Название'?></label>
                <div class="invalid-feedback name_error">
                    Пожалуйста, выберите корректное значение
                </div>
            </div>


            <button id="create" class="btn btn-primary">Добавить</button>

        </form>
        <?php endif; ?>

    </div>
</div>

<?php
$script = <<< JS
    jQuery(document).ready(function () {
        var elem;
        var url;
        data = {

        };
        if($("#update").length){
                var elem = $("#update");
                var url = "/city/ajax";
                data.id = elem.data("id");

                actionCity(elem,url,data);
                return;
        }
        if($("#create").length){
            console.log($("#create"), "CREATE");
                var elem = $("#create");
                var url = "/city/create";
                actionCity(elem,url,data);
                return;
        }
        
        
        function actionCity(elem,url,data){
            elem.click(function(e) {
            var input = elem.closest('.parent').find('.name');
            var name = elem.closest('.parent').find('.name').val();
            data.name = name;
           $.ajax({
                url: url,
                method: "POST",
                data: data,
                dataType: "json",
                success: function (data) {
                    if(data.name){
                        $('.name_error').show();
                        input.val('');
                        alert("Некорректный ввод");
                        return;
                    }
                    input.val(name);
                    window.location.href = "index";
                    
                },

            }); 
            e.preventDefault();
        }); 

        }

              
    });

JS;
$this->registerJs($script);
?>

views/city/_single.php
<?php


use yii\helpers\Url;
use yii\helpers\Html;
?>

<li class="list-group-item list-group-item-action d-flex justify-content-between">
    <span class="me-3">
        <?=Html::encode($model->name) ?>
    </span>
    <span class="text-nowrap">
        <a href="<?php echo Url::to(['/city/update?id='.$model->id.''], true);?>" class="text-decoration-none me-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil"
                viewBox="0 0 16 16">
                <path
                    d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
            </svg>
        </a>

        <a data-id="<?= $model->id?>" data-bs-toggle="modal" data-bs-target="#exampleModal" href="#"
            class="text-decoration-none data">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash"
                viewBox="0 0 16 16">
                <path
                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                <path fill-rule="evenodd"
                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
            </svg>
        </a>
    </span>
</li>

views/city/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\City */

$this->title = Yii::t('app', 'Create City');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Cities'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="city-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/city/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CityeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Cities');
$this->params['breadcrumbs'][] = $this->title;
$this->registerJsFile(Yii::$app->request->baseUrl . '/js/remove_category.js?t=' . time(), ['depends' => [yii\web\JqueryAsset::className()]]);
?>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cancel" data-bs-dismiss="modal">Отмена</button>
                <div id="add"></div>
            </div>
        </div>
    </div>
</div>
<h1 class="my-md-5 my-4">Типы товара</h1>
<a class="btn btn-primary mb-4" href="<?php echo Url::to(['/city/create'], true);?>" role="button">Добавить</a>
<div class="row">
    <div class="col-md-6">
        <ul class="list-group mb-4">
            <li class="list-group-item d-flex justify-content-between">
                <strong>Название</strong>
            </li>
            <?php echo ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => '_single',
                        'layout' => "{items}{pager}",
                        'pager' => [
                        'firstPageLabel' => 'first',
                        'lastPageLabel' => 'last',
                        'nextPageLabel' => 'next',
                        'prevPageLabel' => 'previous',
                        'maxButtonCount' => 3,
                        ],
            ]);?>


        </ul>
    </div>

views/city/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cities */


$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Cities'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="city-update">




    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/city/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cities */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Cities'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="city-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
        ],
    ]) ?>

</div>