controllers/CityController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cities;
use app\models\CitySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\filters\AccessControl;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CityController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'ajax', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'ajax', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

        
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cities models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CitySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cities model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Cities();
        if ( 
            Yii::$app->request->post()
            && Yii::$app->request->isAjax
            )   {
            $_POST['name'] = Html::encode($_POST['name']);
            $model->name = $_POST['name'];
            if(!$model->validate()) {
                print_r(json_encode($model->getErrors()));
                exit();
            }
            if($model->save()) {
               print_r(json_encode('success'));
               exit();
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Cities model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ( $model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    public function actionAjax()
    {
        if (!empty($_POST) && $_POST['id']) {
            if (Yii::$app->request->post() && Yii::$app->request->isAjax) {
                $model = $this->findModel($_POST['id']);
                $_POST['name'] = Html::encode($_POST['name']);
                $model->name = $_POST['name'];
                if (!$model->validate()) {        
                    print_r(json_encode($model->getErrors()));
                    exit();
                }
                if ($model->save()) {
                   print_r(json_encode('success'));
                   exit();
                }
            }            
        };    
    }

    /**
     * Deletes an existing Cities model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete()
    {     
        if (!empty($_POST)) {
           $this->findModel((int)$_POST['id'])->delete();
            print_r (json_encode('success'));
            exit();
        }
        die('fail');
    }

    /**
     * Finds the Cities model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cities the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cities::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/MaterialController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Material;
use app\models\MaterialSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\filters\AccessControl;
use app\models\Photo;
use app\models\City;
use app\models\NewsCity;

/**
 * MaterialController implements the CRUD actions for Material model.
 */
class MaterialController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'ajax', 'delete', 'ajax2','upload','favorites'],
                'rules' => [
                    [
                        'actions' => ['index','create', 'update', 'ajax', 'delete','ajax2','upload','favorites'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST', 'GET'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {            
        if ($action->id == 'create' ||$action->id == 'upload') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    /**
     * Lists all Material models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MaterialSearch();
        $limit = 6;    
        $params =[];
        if (
            !empty($_GET) &&
            isset($_GET['page_count']) &&
            $_GET['page_count']
        )   {
            $params['page_count'] =  (int)$_GET['page_count'];
        }
        if ( 
            !empty($_GET) && 
            isset($_GET['city_id']) 
            && $_GET['city_id']
        ) {
            $params['city_id'] = $_GET['city_id'];
        };
         //Base Search
        if (!isset($_GET['page_count'])) {
            $params['page_count'] = 1;
        }
        $result = $searchModel->asyncSearch($params);
        if (!isset($result['result'])) {
            $result['result'] = [];
            $result['pages'] = [];
        }
        return $this->render('index', [
            "result" =>$result['result'],
            "pages"=>$result['pages'],
            'favorit'  => null,
            'filter_id'=>null,
        ]);
    }
   
    public function actionAjax()
    { 
        //Search 
        if( 
            !empty($_GET) && 
            isset($_GET['val']) && 
            $_GET['val']
        )   {
                $params = [];
                if(isset($_GET['page_count'])) {
                    $params['page_count'] = Html::encode($_GET['page_count']);
                }
                $searchModel = new MaterialSearch();
                $params['val'] = $_GET['val'];
                $result = $searchModel->asyncSearch($params);
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                if (!isset($result['result'])) {
                    $result['result'] = [];
                    $result['pages'] = [];
                    $result['val'] = [];
                }
                $results = [
                    'val' =>$result['val'],
                    'paginated_search'=>$result['pages'],
                    'result' => $result['result'],
                    
                ];
                //var_dump($results); exit();
                return $results;  
        }   else   {
            return $this->redirect(['index']);

        }
    }
    /**
     * Creates a new Material model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {    
        $model = new Material();
        if  (Yii::$app->request->post() && Yii::$app->request->isAjax) {
            $_POST['title'] = Html::encode($_POST['title']);
            $_POST['description'] = Html::encode($_POST['description']);
            $_POST['text'] = Html::encode($_POST['text']);
            $model->title = $_POST['title'];
            $model->description = $_POST['description'];
            $model->text = $_POST['text'];
            $model->city_id = $_POST['city'];
            if  (!$model->validate()) {
                \Yii::$app->getSession()->setFlash('error', 'Некорректный ввод');
                print_r(json_encode($model->getErrors()));
                exit();
            }
            if ($model->save()) {
                if(!Material:: getFields(Yii::$app->user->id)){
                    Material::createDefaultFields(Yii::$app->user->id);            
                }
                Yii::$app->db->createCommand()->insert('news_city', [
                'news_id' => intval($model->id),
                'city_id' => intval($_POST['city']),
                ])->execute();
                \Yii::$app->getSession()->setFlash('success', 'Сохранено');  
                $result=[];
                $result['id']=$model->id;
                print_r(json_encode($result));
                exit();
            }
        }
        if (Yii::$app->request->post() && !Yii::$app->request->isAjax) {
            $model->load(Yii::$app->request->post());
        }
        return $this->render('create', [
            'model' => $model, 'update'=>true
        ]);
       
    }
    public function actionFavorites($id)
    {
        if ($id) {
            Yii::$app->db->createCommand()->insert('news_users', [
                'news_id' => intval($id),
                'user_id' => intval(Yii::$app->user->id),
            ])->execute();
            return $this->redirect('/material/index');
        }
    }
    public function actionUpload()
    { 
        if (Yii::$app->request->post()) {
            if (isset($_FILES['photo']) && $_POST['id']) {
                $filename = $_FILES['photo']['name'];
                if (!isset($_FILES['photo']['type'])) {
                    echo('NO TYPE');
                    echo 'fatal error: no support type'; exit;

                }
                $mime_type = $_FILES['photo']['type'];
                $allowed_file_types = ['image/png', 'image/jpeg'];
                if (!in_array($mime_type, $allowed_file_types)) {
                    echo 'Not allowed type '. $mime_type;
                     exit;
                }
                $e = explode('.', $filename);
                $ext = end($e);
                $name = time() . '.' . $ext;
                $material = Material::findOne($_POST['id']);
                if (isset($_POST['is_new_photo'])) {
                    $model= new Photo();
                } else { 
                    $model = Photo::findOne($material->photo_id);
                }
                if ($material->photo_id == null) {
                    $model= new Photo();
                }
                $model->name = $name;  
                $uploadDirFull = '/uploads/full/';
                $path = (Yii::getAlias('@webroot') . $uploadDirFull . $name);
                try {
                    if (is_uploaded_file ($_FILES ['photo'] ['tmp_name'])) {
                            move_uploaded_file ($_FILES ['photo'] ['tmp_name'],
                            Yii::getAlias('@webroot') . $uploadDirFull . $name);
                    };
                } catch (Exception $e) {
                    echo'Error:', $e->getMessage (). PHP_EOL;
                };
                if ($ext == 'png') {
                    $image = imagecreatefrompng(Yii::getAlias('@webroot') . '/uploads/full/' . $name);
                    $im = imagecreatefrompng(Yii::getAlias('@webroot') . '/uploads/full/' . $name);
                    $im2 = imagecrop($im, ['x' => 0, 'y' => 0, 'width' => 50, 'height' => 70]);
                    $im2 = imagescale($im, 50, 70);
                    if ($im2 !== FALSE) {
                        imagepng($im2, Yii::getAlias('@webroot') . '/uploads/thumbs/' . $name);
                        imagedestroy($im2);
                    }
                    imagedestroy($im);
                } else {    
                    if (file_exists(Yii::getAlias('@webroot') . '/uploads/full/' . $name)) {
                        $image = imagecreatefromjpeg(Yii::getAlias('@webroot') . '/uploads/full/' . $name);
                        $im = imagecreatefromjpeg(Yii::getAlias('@webroot') . '/uploads/full/' . $name);
                        $im2 = imagecrop($im, ['x' => 0, 'y' => 0, 'width' => 50, 'height' => 70]);
                        $im2 = imagescale($im, 50, 70);
                        if ($im2 !== FALSE) {
                            imagejpeg($im2, Yii::getAlias('@webroot') . '/uploads/thumbs/' . $name);
                            imagedestroy($im2);
                        }
                        imagedestroy($im);     
                    } else { 
                    echo('Error');
                    exit();
                    }  
                }
                $model->full = $model->thumbs=$name;
                if (!$model->save()) {
                    echo('STOP');
                    var_dump($model->getErrors());
                };
                if ($material) {
                    $material->photo_id = $model->id;
                    if (!$material->save()) {
                        var_dump($material->getErrors());exit();
                    };
                }
                return $this->redirect(['index']);    
            }

        }
        
    }
    /**
     * Updates an existing Material model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

views/material/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use app\models\Material;
use app\models\Cities;
use dosamigos\selectize\SelectizeDropDownList ;
use vova07\imperavi\Widget;


/* @var $this yii\web\View */
/* @var $model app\models\Material */
/* @var $form yii\widgets\ActiveForm */

if (isset($_GET['id'])) {
    $this->title = Yii::t('app', 'Редактировать');
} else {
    $this->title = Yii::t('app', 'Добавить новость');
}
if ( 
    isset($model['id']) && 
    !empty($model['id'])
)   {
    $city_name = Cities::getCityName($model->city_id);
    $photo = Material::getPhoto($model->photo_id);
    $news = Material::getNews($model['id'],$model->city_id, $model->title);
} else {
    $photo = null;
}
$city_list = Cities::getCityList();
?>

<h1 class="my-md-5 my-4"><?= Html::encode($this->title) ?></h1>
<div class="row">
    <div class="col-lg-5 col-md-8">
        <form class="parent">
            <div class="form-floating mb-3">
                <input value="<?= !empty($model['id']) ? $model['description'] : ''?>" name="description" type="text"
                    class="form-control sku" placeholder="Введите код товара" id="floatingName">
                <label for="floatingName">Описание</label>
                <div class="invalid-feedback sku_error">
                    Пожалуйста, заполните поле
                </div>
            </div>
            <div class="form-floating mb-3">
                <input value="<?= !empty($model['id']) ? $model['title'] : ''?>" name="title" type="text"
                    class="form-control title" placeholder="Напишите название" id="floatingName">
                <label for="floatingName"> Название</label>
                <div class="invalid-feedback title_error">
                    Пожалуйста, заполните поле
                </div>
            </div>
            <div class="form-floating mb-3">
                <textarea value="<?= !empty($model['id']) ? $model['text'] : ''?>" name="text" type="text"
                    class="form-control quantity" placeholder="Напишите название"
                    id="floatingName"><?= !empty($model['id']) ? $model['text'] : ''?> </textarea>
                <label for="floatingName"> Текст</label>
                <div class="invalid-feedback quantity_error">
                    Пожалуйста, заполните поле
                </div>
            </div>
            <div class="form-floating mb-3">
                <select name="type" class="form-select type" id="floatingSelectCategory">
                    <option value="<?= !empty($model['id']) ? $model['city_id'] : ''?>" selected>
                        <?= !empty($model['id']) ? $city_name : 'Выберите город'?>
                    </option>
                    <?php
                        if (!empty($city_list)) {
                        foreach ($city_list as $key => $val)  {
                    ?>
                    <option value="<?php echo $key;?>"><?php echo $val;?></option>
                    <?php
                        }
                      }
                    ?>
                </select>
                <label for="floatingSelectCategory">Город</label>
                <div class="invalid-feedback  type_error">
                    Пожалуйста, заполните поле
                </div>
            </div>


            <?php if (isset($_GET['id'])): ?>
            <button data-id="<?= $model['id']?>" id="update" class="btn btn-primary mb-3">Добавить</button>
            <?php endif; ?>
            <?php if (!isset($_GET['id'])): ?>
            <button data-id="<?= $model['id']?>" id="create" class="btn btn-primary mb-3">Добавить</button>
            <?php endif; ?>
        </form>

    </div>
    <div class="col-lg-5">
        <?php if(!empty($news)) :?>
        Похожие новости
        <?php endif?>
        <div class="table-responsive">
            <?php if(!empty($news)) :?>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Изображение</th>
                        <th scope="col">Описание</th>
                        <th scope="col">Название</th>
                        <th scope="col">Город</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <form class="parent" method="POST" action="<?php echo Url::to(['/material/delete'], true);?>">
                    <?=
                        Html::hiddenInput(
                        Yii::$app->request->csrfParam,
                        Yii::$app->request->csrfToken
                        );
                    ?>
                    <tbody id="body">
                        <?php foreach($news as $item):?>
                        <tr>
                            <td>
                                <? if($item['photo_id']) :?>
                                <img
                                    src="<?php echo Url::to(['/uploads/thumbs/'.Material::getPhotoThumbs($item['photo_id']).''], true);?>">
                                <? endif ?>
                            </td>
                            <td>
                                <?= $item['description']  ?>
                            </td>
                            <td>
                                <a
                                    href="<?php echo Url::to(['/material/update/?id=' . $item['id'] .''], true);?>"><?=  Html::encode($item['title'])  ?></a>
                            </td>
                            <td><?php echo Cities::getCityName($item['city_id'])  ?></td>
                            <td class="text-nowrap text-end">
                                <a href="<?php echo Url::to(['/material/update/?id=' . $item['id'] .''], true);?>"
                                    class="text-decoration-none me-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                        class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path
                                            d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                    </svg>
                                </a>
                                <?php if(!Material::userHasNews($item['id'])):?>
                                <a href="<?php echo Url::to(['/material/favorites/?id=' . $item['id'] .''], true);?>"
                                    type="button" class="btn btn-danger">Избранное</a>
                                <?php endif; ?>

                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>

                </form>
            </table>
            <?php endif  ?>

        </div>
    </div>
    <div class="col-lg-5 col-md-8">
        <form class="upload_file" method="POST" enctype="multipart/form-data" style="display:none;"
            action="<?php echo Url::to(['/material/upload'], true);?>">

            <input value="<?= !empty($model['id'])&& $photo ? $photo->id : ''?>" name="photo" type="file"
                class="form-control photo" placeholder="Напишите название" id="floatingName">
            <?php if ($photo): ?>
            <img src="<?php echo Url::to(['/uploads/thumbs/'.Material::getPhotoThumbs($photo->id).''], true);?>">
            <?php endif; ?>
            <div class="invalid-feedback file_error">
                Пожалуйста, заполните поле
            </div>
            <?php if (!$model['id']): ?>
            <input name="is_new_photo" type="hidden">
            <?php endif; ?>
            <input name="id" id="upload" value="<?= !empty($model['id']) ? $model['id'] : ''?>" type="hidden">
            <button style="margin-left:70%" class="btn btn-primary mt-2">Upload</button>
        </form>
    </div>

</div>
</div>
<?php
$script = <<< JS
    jQuery(document).ready(function () {
        var elem;
        var url;
        data = {

        };
        if($("#update").length){
                console.log($("#update"), "UPDATE");
                var elem = $("#update");
                var url = "/material/ajax2";
                data.id = elem.data("id");
                $(".upload_file").show();
                actionMaterial(elem,url,data);
                return;
        }
        if($("#create").length){
            console.log($("#create"), "THIS CASE");
                var elem = $("#create");
                var url = "/material/create";
                $(".upload_file").hide();
                actionMaterial(elem,url,data);
                return;
        }
        function actionMaterial(elem,url,data){
            elem.click(function(e) {
                $(".invalid-feedback").css("display","none");
                var p = elem.closest('.parent'); 
                console.log(p, 'P');
                var city = p.find('.type').val();
                var title = p.find('.title').val();
                var description = p.find('.sku').val(); 
                var text = p.find('.quantity').val();
                if (city== "Выберите город") {
                    city = '';
                } 
                data.city = city;
                data.title = title;
                data.description = description;
                data.text = text;
                $.ajax({
                    url: url,
                    method: "POST",
                    data: data,
                    dataType: "json",
                    success: function (data) {         
                        if (data.description || data.city_id || data.title || data.text) {
                            if (data.city_id) {
                                $('.type_error').css("display","block");
                            } 
                            if(data.description ){
                                $('.sku_error').css("display","block");
                            }
                            if(data.text){
                                $('.quantity_error').css("display","block");
                            } 
                            if(data.title){
                                $('.title_error').css("display","block");
                            } 
                            $('.alert-danger').css('display', 'block');
                            $('.alert-danger').scrollTop();
                            return false;              
                        }

                        if($("#update").length){
                            p.find('.type').val(city);
                            p.find('.sku').val(description);
                            p.find('.title').val(title);
                            p.find('.quantity').val(text);
                            $('.alert-success').css('display', 'block');
                            $('.alert-danger').css('display', 'none');
                            $('.alert-success').scrollTop();
                            return false;
                        }
                        if($("#create").length){
                            p.find('.type').val(city);
                            p.find('.sku').val(description);
                            p.find('.title').val(title);
                            p.find('.quantity').val(text);
                            $("#upload").val(data.id);
                            $('.alert-success').css('display', 'block');
                            $('.alert-danger').css('display', 'none');
                            $('.alert-success').scrollTop();
                            $(".upload_file").css('display', "block");
                            return false;
                        }  
                    },
                }); 
                e.preventDefault();
            }); 

        }
           
    });

JS;
$this->registerJs($script);
?>

views/material/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Material */


$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Materials'), 'url' => ['index']];

?>
<div class="material-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/material/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Material */


$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Materials'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="material-update">



    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>